# nacos配置
server:
  port: 88

dubbo:
  scan:
    base-packages: com.bilibili.springcloud.alibaba.impl
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost

spring:
  application:
    name: nacos-dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
        namespace: fcfd1bb8-1486-4280-a337-70a6ff27a2ad
      config:
        server-addr: localhost:8848 #Nacos作为配置中心地址
        file-extension: yaml #指定yaml格式的配置
        group: DEV_GROUP
        namespace: fcfd1bb8-1486-4280-a337-70a6ff27a2ad
  main:
    allow-bean-definition-overriding: true